"""EPUB export for StoryForge AI stories."""

import re
from pathlib import Path


def _html_paragraphs(text: str) -> str:
    paragraphs = []
    for block in text.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        if block.startswith("#"):
            level = len(re.match(r"^(#+)", block).group(1))
            heading = re.sub(r"^#+\s*", "", block)
            paragraphs.append(f"<h{min(level, 3)}>{heading}</h{min(level, 3)}>")
        else:
            block = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", block)
            block = re.sub(r"\*(.+?)\*", r"<em>\1</em>", block)
            paragraphs.append(f"<p>{block}</p>")
    return "\n".join(paragraphs)


def export_epub(
    title: str,
    body: str,
    output_path: str,
    author: str = "StoryForge AI",
    summary: str = "",
    tags: str = "",
) -> str:
    """Export story to EPUB. Returns the output file path."""
    try:
        from ebooklib import epub
    except ImportError:
        raise ImportError("Install EbookLib: pip install EbookLib")

    book = epub.EpubBook()
    book.set_identifier(f"storyforge-{title.lower().replace(' ', '-')}")
    book.set_title(title)
    book.set_language("en")
    book.add_author(author)

    if tags:
        for tag in tags.split(","):
            book.add_metadata("DC", "subject", tag.strip())

    intro = f"<p><em>{summary}</em></p>" if summary else ""
    content = epub.EpubHtml(title=title, file_name="chapter.xhtml", lang="en")
    content.content = (
        f"<html><head><title>{title}</title></head><body>"
        f"<h1>{title}</h1>{intro}{_html_paragraphs(body)}"
        f"<hr/><p><em>Generated by {author}</em></p></body></html>"
    )

    book.add_item(content)
    book.toc = [content]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", content]

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    epub.write_epub(output_path, book)
    return output_path
