"""PDF export for StoryForge AI stories."""

import os
import re
from pathlib import Path


def _strip_markdown(text: str) -> str:
    text = re.sub(r"^#+\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"^---+$", "", text, flags=re.MULTILINE)
    return text.strip()


def export_pdf(
    title: str,
    body: str,
    output_path: str,
    author: str = "StoryForge AI",
    summary: str = "",
) -> str:
    """Export story to PDF. Returns the output file path."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("Install fpdf2: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.multi_cell(0, 12, title)
    pdf.ln(4)

    if summary:
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 6, _strip_markdown(summary))
        pdf.ln(6)

    pdf.set_font("Helvetica", "", 11)
    clean_body = _strip_markdown(body)
    for paragraph in clean_body.split("\n\n"):
        paragraph = paragraph.strip()
        if paragraph:
            pdf.multi_cell(0, 6, paragraph)
            pdf.ln(3)

    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, f"Generated by {author}", align="C")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pdf.output(output_path)
    return output_path
